spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgres://localhost:5432/commerce
    username: commerce
    password: commerce
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
  data:
    redis:
      host: localhost
      port: 6379